"""Change column name

Revision ID: 13d4a5723cc5
Revises: 42aa709e77e8
Create Date: 2022-05-02 18:19:29.922692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13d4a5723cc5"
down_revision = "42aa709e77e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("languages", sa.Column("code", sa.String(), nullable=False))
    op.drop_column("languages", "ietf_tag")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "languages",
        sa.Column("ietf_tag", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("languages", "code")
    # ### end Alembic commands ###
