"""Add relationship between models and users tables

Revision ID: 2c2c0bdd0ba6
Revises: 930b4a0511c2
Create Date: 2022-01-29 14:38:34.573929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c2c0bdd0ba6'
down_revision = '930b4a0511c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('services_created_by_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('services', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_created_by_fkey', 'services', 'users', ['created_by'], ['id'])
    op.drop_column('services', 'created_by_user_id')
    # ### end Alembic commands ###
