"""Add fcm_token relationship

Revision ID: 36ad938d29e8
Revises: a100ab355ec8
Create Date: 2022-06-13 19:11:21.035055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "36ad938d29e8"
down_revision = "a100ab355ec8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fcm_tokens",
        sa.Column(
            "last_updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("fcm_tokens", "created_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fcm_tokens",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("fcm_tokens", "last_updated_at")
    # ### end Alembic commands ###
