"""Add unique requirement to token column in fcm_tokens table

Revision ID: 3b6341446c29
Revises: 774cf7cd5ff1
Create Date: 2022-09-15 23:33:36.577726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b6341446c29"
down_revision = "774cf7cd5ff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "appointment_slots",
        "appointments",
        ["occupied_by_appointment"],
        ["id"],
        use_alter=True,
    )
    op.create_unique_constraint(None, "fcm_tokens", ["token"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fcm_tokens", type_="unique")
    op.drop_constraint(None, "appointment_slots", type_="foreignkey")
    # ### end Alembic commands ###
