"""Update services table

Revision ID: 425dc77cbc41
Revises: 7b7d092c8b80
Create Date: 2022-02-05 17:25:58.385333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '425dc77cbc41'
down_revision = '7b7d092c8b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('create_event_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('services_created_by_user_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'service_events', ['create_event_id'], ['id'])
    op.drop_column('services', 'created_by_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_by_user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_created_by_user_id_fkey', 'services', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('services', 'create_event_id')
