"""Add break_time column

Revision ID: 42aa709e77e8
Revises: 9a966252039e
Create Date: 2022-05-01 23:24:50.583194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42aa709e77e8'
down_revision = '9a966252039e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_slots', sa.Column('break_time', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'appointment_slots', 'appointments', ['occupied_by_appointment'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment_slots', type_='foreignkey')
    op.drop_column('appointment_slots', 'break_time')
    # ### end Alembic commands ###
