"""Add description field to Service table

Revision ID: 58620602b811
Revises: b830a90b4d64
Create Date: 2024-03-24 19:38:57.276963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58620602b811'
down_revision = 'b830a90b4d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointment_slots', 'appointments', ['occupied_by_appointment'], ['id'], use_alter=True)
    op.add_column('services', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'description')
    op.drop_constraint(None, 'appointment_slots', type_='foreignkey')
    # ### end Alembic commands ###
