"""Add user_id foreign key to the settings table

Revision ID: 59f57aaec089
Revises: 390305616fce
Create Date: 2022-01-03 00:44:11.713353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f57aaec089'
down_revision = '390305616fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_column('settings', 'user_id')
    # ### end Alembic commands ###
