"""Update services table and add operations table

Revision ID: 930b4a0511c2
Revises: c6e4ec7b47ff
Create Date: 2022-01-29 14:16:33.114954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '930b4a0511c2'
down_revision = 'c6e4ec7b47ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('performed_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subject', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('average_time_minutes', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('services', 'created_by',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('services', 'time_minutes')
    op.drop_column('services', 'user_defined')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('user_defined', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('time_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('services', 'created_by',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('services', 'deleted')
    op.drop_column('services', 'average_time_minutes')
    op.drop_table('operations')
    # ### end Alembic commands ###
