"""Create additional fields

Revision ID: af30628f6e52
Revises: e19c6bee7c0b
Create Date: 2022-01-02 18:10:39.386873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af30628f6e52'
down_revision = 'e19c6bee7c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('canceled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('archival', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('services', sa.Column('available', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'sex', new_column_name='gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender', new_column_name='sex')
    op.drop_column('users', 'disabled')
    op.drop_column('services', 'available')
    op.drop_column('appointments', 'archival')
    op.drop_column('appointments', 'canceled')
    # ### end Alembic commands ###
