"""Update users table

Revision ID: b1b5b61d35c8
Revises: af30628f6e52
Create Date: 2022-01-02 18:18:15.636177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b5b61d35c8'
down_revision = 'af30628f6e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission_level', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'password', new_column_name='hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    op.drop_column('users', 'permission_level')
    op.alter_column('users', 'hashed_password', new_column_name='password')
    # ### end Alembic commands ###
