"""Change columns order

Revision ID: bfba9da5d9d2
Revises: b1b5b61d35c8
Create Date: 2022-01-02 18:20:21.210517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfba9da5d9d2'
down_revision = 'b1b5b61d35c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'permission_level')
    op.drop_column('users', 'verified')
    op.add_column('users', sa.Column('permission_level', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
