"""Add description column to the services table

Revision ID: c611c921c1df
Revises: 8e0ba16d64f8
Create Date: 2022-01-28 01:00:34.197103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c611c921c1df'
down_revision = '8e0ba16d64f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'description')
    # ### end Alembic commands ###
