"""Update services table

Revision ID: c6e4ec7b47ff
Revises: d32fa082f1f8
Create Date: 2022-01-28 01:07:08.398217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e4ec7b47ff'
down_revision = 'd32fa082f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('time_minutes', sa.Integer(), nullable=False))
    op.drop_column('services', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('services', 'time_minutes')
    # ### end Alembic commands ###
