"""Update services table

Revision ID: d32fa082f1f8
Revises: c611c921c1df
Create Date: 2022-01-28 01:05:19.287823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32fa082f1f8'
down_revision = 'c611c921c1df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('min_price', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('max_price', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'services', ['name'])
    op.drop_column('services', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_column('services', 'max_price')
    op.drop_column('services', 'min_price')
    # ### end Alembic commands ###
