name: Build and deploy code

on:
  push:
    branches:
      - "main"

jobs:
  build:
    env:
      API_VERSION: ${{secrets.API_VERSION}}
      API_TITLE: ${{secrets.API_TITLE}}
      BASE_URL: ${{secrets.BASE_URL}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      API_SECRET_KEY: ${{secrets.API_SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_SERVER: ${{secrets.MAIL_SERVER}}
      MAIL_TLS: ${{secrets.MAIL_TLS}}
      MAIL_SSL: ${{secrets.MAIL_SSL}}
      USE_CREDENTIALS: ${{secrets.USE_CREDENTIALS}}
      VALIDATE_CERTS: ${{secrets.VALIDATE_CERTS}}
      MAIL_FROM_NAME: ${{secrets.MAIL_FROM_NAME}}
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Installing Python v.3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Updating pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Deploying to manjaro server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: ${{secrets.DEPLOYMENT_USERNAME}}
          password: ${{secrets.DEPLOYMENT_PASSWORD}}
          script: |
            cd app/src
            git pull
            sudo systemctl restart api
