name: Build and deploy code

on:
  push:
    branches:
      - "main"

jobs:
  build:
    env:
      API_VERSION: 0.1 Alpha
      API_TITLE: Zołza Hairstyles API
      BASE_URL: /api
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Test1234
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: zolza_hairstyles_dev
      API_SECRET_KEY: sadasdas
      ALGORITHM: sadas
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      MAIL_USERNAME: zhairstylestest@gmail.com
      MAIL_PASSWORD: Test123$
      MAIL_FROM: zhairstylestest@gmail.com
      MAIL_PORT: 587
      MAIL_SERVER: smtp.gmail.com
      MAIL_TLS: true
      MAIL_SSL: false
      USE_CREDENTIALS: true
      VALIDATE_CERTS: true
      MAIL_FROM_NAME: no-reply-zolza-hairstyles.pl
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Installing Python v.3.9
        uses: actions/setup-python@v2
        with:
          pyton-version: "3.9"
      - name: Updating pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
